# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400, verbose_name='komentarz')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(choices=[(1, 'mężczyzna'), (2, 'kobieta')], verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run.Person', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Krótki opis'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='distance',
            field=models.CharField(max_length=8, verbose_name='Dystans'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Numer'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='pace',
            field=models.IntegerField(choices=[(1, 'wolniej niż 7:00/km'), (2, '6:45 - 7:00/km'), (3, '6:30 - 6:45/km'), (4, '6:15 - 6:30/km'), (5, '6:00 - 6:15/km'), (6, '5:45 - 6:00/km'), (7, '5:30 - 5:45/km'), (8, '5:15 - 5:30/km'), (9, '5:00 - 5:15/km'), (10, '4:45 - 5:00/km'), (11, '4:30 - 4:45/km'), (12, '4:15 - 4:30/km'), (13, '4:00 - 4:15/km'), (14, '3:45 - 4:00/km')], verbose_name='Tempo'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='street',
            field=models.CharField(max_length=64, verbose_name='Ulica/miejsce'),
        ),
        migrations.AlterField(
            model_name='trening',
            name='time',
            field=models.TimeField(verbose_name='godzina'),
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run.Person', verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='trening',
            name='comments',
            field=models.ManyToManyField(to='run.Comments'),
        ),
    ]
