# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_auto_20170705_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trening',
            new_name='Training',
        ),
    ]
